/**
 * Generates src/generated/fieldDescriptors.ts from the VehicleType interface
 * in src/generated/types.ts using ts-morph for AST inspection.
 *
 * Usage:
 *   tsx scripts/generate-field-descriptors.ts           # write file
 *   tsx scripts/generate-field-descriptors.ts --check    # exit 1 if stale
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Project, type InterfaceDeclaration, type PropertySignature, SyntaxKind } from 'ts-morph';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');
const TYPES_PATH = resolve(PKG_ROOT, 'src/generated/types.ts');
const OUT_PATH = resolve(PKG_ROOT, 'src/generated/fieldDescriptors.ts');

const HEADER = `// AUTO-GENERATED by scripts/generate-field-descriptors.ts — do not edit manually
// Source: src/generated/types.ts (VehicleType interface)`;

// ── Known enum const-array names keyed by their type-alias name ──
// The script detects these automatically from "typeof X" patterns in the type source,
// but we keep a fallback map for inline types like `(typeof FARE_CLASSES)[number]`.
const ENUM_CONST_MAP: Record<string, string> = {
  AllPublicTransportModesEnumeration: 'TRANSPORT_MODES',
  PropulsionTypeEnumeration: 'PROPULSION_TYPES',
  FuelTypeEnumeration: 'FUEL_TYPES',
};

// ── Helpers ──

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Given a property from an interface, determine the FieldDescriptor kind
 * and, for enums, the const-array name.
 */
function resolveFieldKind(
  prop: PropertySignature,
  project: Project
): {
  kind: string;
  allowed?: string;
  subInterface?: InterfaceDeclaration;
  isRef?: boolean;
  refTarget?: string;
} {
  const typeNode = prop.getTypeNode();
  if (!typeNode) {
    // Fall back to type checker
    const t = prop.getType();
    if (t.isString()) return { kind: 'string' };
    if (t.isNumber()) return { kind: 'number' };
    if (t.isBoolean()) return { kind: 'boolean' };
    return { kind: 'string' }; // safe fallback
  }

  const typeText = typeNode.getText();

  // Array types: X[] or Array<X>
  if (typeNode.getKind() === SyntaxKind.ArrayType) {
    const elementNode = typeNode.getFirstChild();
    if (elementNode) {
      const elemText = elementNode.getText();
      // Check if element is an enum type
      const enumConst = resolveEnumConst(elemText, project);
      if (enumConst) {
        return { kind: 'enum[]', allowed: enumConst };
      }
      // Check if element is an interface
      const iface = findInterface(elemText, project);
      if (iface) {
        return { kind: 'array', subInterface: iface };
      }
    }
    return { kind: 'array' };
  }

  // Indexed access type: (typeof FARE_CLASSES)[number]
  if (typeNode.getKind() === SyntaxKind.IndexedAccessType) {
    const constName = extractTypeofConst(typeText);
    if (constName) {
      return { kind: 'enum', allowed: constName };
    }
  }

  // Type reference: could be interface, type alias, or SimpleRef
  if (typeNode.getKind() === SyntaxKind.TypeReference) {
    const refName = typeText;

    // Check if it's a known enum alias
    const enumConst = resolveEnumConst(refName, project);
    if (enumConst) {
      return { kind: 'enum', allowed: enumConst };
    }

    // Check if it's SimpleRef or Ref<T> (both resolve to string at runtime)
    if (typeText === 'SimpleRef') {
      return { kind: 'string', isRef: true };
    }
    const refMatch = typeText.match(/^Ref(?:<'([^']+)'>)?$/);
    if (refMatch) {
      return { kind: 'string', isRef: true, refTarget: refMatch[1] };
    }

    // Check if it resolves to string
    const type = prop.getType();
    if (type.isString()) {
      return { kind: 'string' };
    }

    // Check if it's an interface
    const iface = findInterface(refName, project);
    if (iface) {
      return { kind: 'object', subInterface: iface };
    }
  }

  // Primitives
  if (typeText === 'string') return { kind: 'string' };
  if (typeText === 'number') return { kind: 'number' };
  if (typeText === 'boolean') return { kind: 'boolean' };

  // Array type written as SomeType[]
  if (typeText.endsWith('[]')) {
    const elemName = typeText.slice(0, -2);
    const enumConst = resolveEnumConst(elemName, project);
    if (enumConst) {
      return { kind: 'enum[]', allowed: enumConst };
    }
    const iface = findInterface(elemName, project);
    if (iface) {
      return { kind: 'array', subInterface: iface };
    }
  }

  return { kind: 'string' }; // safe fallback
}

function resolveEnumConst(typeName: string, project: Project): string | undefined {
  // Direct lookup in our known map
  if (ENUM_CONST_MAP[typeName]) {
    return ENUM_CONST_MAP[typeName];
  }

  // Try to find type alias and extract "typeof X" from it
  const sourceFile = project.getSourceFile(TYPES_PATH);
  if (!sourceFile) return undefined;

  const alias = sourceFile.getTypeAlias(typeName);
  if (!alias) return undefined;

  const aliasText = alias.getTypeNode()?.getText() ?? '';
  return extractTypeofConst(aliasText);
}

function extractTypeofConst(text: string): string | undefined {
  // Match patterns like: (typeof FARE_CLASSES)[number]
  const match = text.match(/\(typeof\s+(\w+)\)\s*\[\s*number\s*\]/);
  return match?.[1];
}

function findInterface(name: string, project: Project): InterfaceDeclaration | undefined {
  const sourceFile = project.getSourceFile(TYPES_PATH);
  return sourceFile?.getInterface(name);
}

// ── Schema generation ──

interface FieldEntry {
  kind: string;
  camel: string;
  xml: string;
  allowed?: string;
  schemaRef?: string;
  isAttribute?: boolean;
  isRef?: boolean;
  refTarget?: string;
}

interface SubSchema {
  varName: string;
  fields: FieldEntry[];
}

function interfaceToSchemaName(ifaceName: string): string {
  // TextType → textTypeSchema, PrivateCodeStructure → privateCodeStructureSchema, etc.
  return ifaceName.charAt(0).toLowerCase() + ifaceName.slice(1) + 'Schema';
}

function processInterface(
  iface: InterfaceDeclaration,
  project: Project,
  subSchemas: Map<string, SubSchema>
): FieldEntry[] {
  const fields: FieldEntry[] = [];

  for (const prop of iface.getProperties()) {
    const name = prop.getName();
    const xml = capitalize(name);
    const resolved = resolveFieldKind(prop, project);

    const entry: FieldEntry = {
      kind: resolved.kind,
      camel: name,
      xml,
    };

    if (resolved.allowed) {
      entry.allowed = resolved.allowed;
    }
    if (resolved.isRef) entry.isRef = true;
    if (resolved.refTarget) entry.refTarget = resolved.refTarget;

    const isAttribute = prop
      .getJsDocs()
      .some(doc => doc.getTags().some(tag => tag.getTagName() === 'xmlAttribute'));
    if (isAttribute) {
      entry.isAttribute = true;
    }

    if (resolved.subInterface) {
      const subName = resolved.subInterface.getName();
      const schemaVarName = interfaceToSchemaName(subName);
      entry.schemaRef = schemaVarName;

      // Process sub-interface if not already done
      if (!subSchemas.has(schemaVarName)) {
        // Reserve the slot to prevent infinite recursion
        subSchemas.set(schemaVarName, { varName: schemaVarName, fields: [] });
        const subFields = processInterface(resolved.subInterface, project, subSchemas);
        subSchemas.set(schemaVarName, { varName: schemaVarName, fields: subFields });
      }
    }

    fields.push(entry);
  }

  return fields;
}

function formatFieldEntry(entry: FieldEntry, indent: string): string {
  const parts: string[] = [
    `kind: '${entry.kind}'`,
    `camel: '${entry.camel}'`,
    `xml: '${entry.xml}'`,
  ];

  if (entry.isAttribute) {
    parts.push(`isAttribute: true`);
  }
  if (entry.isRef) {
    parts.push(`isRef: true`);
  }
  if (entry.refTarget) {
    parts.push(`refTarget: '${entry.refTarget}'`);
  }
  if (entry.allowed) {
    parts.push(`allowed: ${entry.allowed}`);
  }
  if (entry.schemaRef) {
    parts.push(`schema: ${entry.schemaRef}`);
  }

  const inner = parts.join(', ');
  const singleLine = `${indent}{ ${inner} },`;

  // Keep lines under 100 chars when possible
  if (singleLine.length <= 100) {
    return singleLine;
  }

  // Multi-line format
  const lines = [`${indent}{`];
  for (const part of parts) {
    lines.push(`${indent}  ${part},`);
  }
  lines.push(`${indent}},`);
  return lines.join('\n');
}

function generateOutput(
  subSchemas: Map<string, SubSchema>,
  mainFields: FieldEntry[],
  usedEnumConsts: Set<string>
): string {
  const lines: string[] = [HEADER, ''];

  // Imports
  lines.push("import type { FieldDescriptor } from '../fieldSchema.js';");

  if (usedEnumConsts.size > 0) {
    const imports = [...usedEnumConsts].sort().join(', ');
    lines.push(`import { ${imports} } from './types.js';`);
  }

  // Sub-schemas
  for (const [, schema] of subSchemas) {
    lines.push('');
    lines.push(`const ${schema.varName}: FieldDescriptor[] = [`);
    for (const field of schema.fields) {
      lines.push(formatFieldEntry(field, '  '));
    }
    lines.push('];');
  }

  // Main schema
  lines.push('');
  lines.push('export const vehicleTypeSchema: FieldDescriptor[] = [');
  for (const field of mainFields) {
    lines.push(formatFieldEntry(field, '  '));
  }
  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

// ── Main ──

function main() {
  const checkMode = process.argv.includes('--check');

  const project = new Project({
    tsConfigFilePath: resolve(PKG_ROOT, 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });
  project.addSourceFileAtPath(TYPES_PATH);

  const sourceFile = project.getSourceFile(TYPES_PATH)!;
  const vehicleTypeIface = sourceFile.getInterface('VehicleType');
  if (!vehicleTypeIface) {
    console.error('Error: VehicleType interface not found in types.ts');
    process.exit(1);
  }

  const subSchemas = new Map<string, SubSchema>();
  const mainFields = processInterface(vehicleTypeIface, project, subSchemas);

  // Collect all used enum const names
  const usedEnumConsts = new Set<string>();
  function collectEnums(fields: FieldEntry[]) {
    for (const f of fields) {
      if (f.allowed) usedEnumConsts.add(f.allowed);
      if (f.schemaRef) {
        const sub = subSchemas.get(f.schemaRef);
        if (sub) collectEnums(sub.fields);
      }
    }
  }
  collectEnums(mainFields);

  const output = generateOutput(subSchemas, mainFields, usedEnumConsts);

  if (checkMode) {
    let existing: string;
    try {
      existing = readFileSync(OUT_PATH, 'utf-8');
    } catch {
      console.error(`Error: ${OUT_PATH} does not exist. Run 'npm run codegen' first.`);
      process.exit(1);
    }
    if (existing !== output) {
      console.error('fieldDescriptors.ts is out of date. Run `npm run codegen` to regenerate.');
      process.exit(1);
    }
    console.log('fieldDescriptors.ts is up to date.');
    process.exit(0);
  }

  writeFileSync(OUT_PATH, output);
  console.log(`Generated ${OUT_PATH}`);
}

main();
